# Generated by Django 5.0.1 on 2024-01-04 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, help_text='The user namme of the customer.', max_length=50, null=True, verbose_name='user name'),
        ),
    ]
