# Generated by Django 5.0.1 on 2024-01-04 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='on_boarding_complete',
        ),
        migrations.RemoveField(
            model_name='user',
            name='on_boarding_complete_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='registered_ip_address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='social_security_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='verification_date',
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, help_text='The first names of the customer.', max_length=50, null=True, verbose_name='First names'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, help_text='The last names of the customer.', max_length=50, null=True, verbose_name='Last names'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, help_text='The user name of the customer.', max_length=50, null=True, verbose_name='user name'),
        ),
    ]
