# Generated by Django 4.2.9 on 2024-01-05 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_user_on_boarding_complete_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contact_number',
            field=models.CharField(blank=True, help_text='The contact number of the customer.', max_length=15, null=True, verbose_name='Contact number'),
        ),
    ]
