# Generated by Django 4.2.9 on 2024-01-09 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('account', '0004_alter_user_contact_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='contact_number',
            new_name='mobile',
        ),
        migrations.AddField(
            model_name='user',
            name='accept_terms',
            field=models.BooleanField(blank=True, default=False, help_text='Agreements collected from the user, such as acceptance of terms and conditions, or opt in for marketing', null=True, verbose_name='Default Currency ID'),
        ),
        migrations.AddField(
            model_name='user',
            name='agreed_to_data_usage',
            field=models.BooleanField(blank=True, default=False, help_text='Consent to us using the provided data, including consent for us to verify the identity of relevant individuals with our service providers and database owners in accordance with the Identity Verification Terms.', null=True, verbose_name='Agreed to Data Usage'),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, help_text='The country residence of the customer. KYC verification will be applied to this country and customer must provide proof of such residence as relevant in the country of jurisdiction.', max_length=2, null=True, verbose_name='Country of Residence'),
        ),
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(blank=True, choices=[('PERSONAL', 'PERSONAL'), ('BUSINESS', 'BUSINESS')], default='borrower', help_text='Account type', max_length=8, null=True, verbose_name='Account Type'),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
