# Generated by Django 4.2.9 on 2024-01-10 00:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_user_language_user_time_zone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='The unique identifier of an object.', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when the record was created. The date and time \n            are displayed in the Timezone from where request is made. \n            e.g. 2019-14-29T00:15:09Z for April 29, 2019 0:15:09 UTC', verbose_name='Created')),
                ('modified_date', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was modified. The date and \n            time are displayed in the Timezone from where request \n            is made. e.g. 2019-14-29T00:15:09Z for April 29, 2019 0:15:09 UTC\n            ', null=True, verbose_name='Updated')),
                ('balance', models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='The customers available Balance for the account', max_digits=300, null=True, verbose_name='Available Balance')),
                ('wallet_id', models.CharField(blank=True, help_text='User Geniotest wallet id is unique to every user, the wallet id contains information about the customer', max_length=20, null=True, unique=True, verbose_name='Geniotest Wallet ID')),
                ('user', models.ForeignKey(help_text='The user for whom address belongs to', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User Profile')),
            ],
            options={
                'verbose_name': 'User Wallet',
                'verbose_name_plural': 'User Wallet',
                'ordering': ('-created_date',),
            },
        ),
    ]
