# Generated by Django 4.2.9 on 2024-01-10 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=5000.0, help_text='The customers available Balance for the account', max_digits=300, null=True, verbose_name='Available Balance'),
        ),
    ]
