# Generated by Django 4.2.9 on 2024-01-11 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_wallet_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verification',
            field=models.BooleanField(blank=True, default=False, help_text='this indicates if the email is been verified by the user using geniopay endpoint', null=True, verbose_name='Email Verification'),
        ),
    ]
