# Generated by Django 4.2.9 on 2024-01-12 00:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_user_email_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='geniopay_key',
            field=models.CharField(blank=True, help_text='this stores the users login key', max_length=100, null=True, verbose_name='GenioPay KEY ID'),
        ),
        migrations.AddField(
            model_name='user',
            name='geniopay_user_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='GenioPay user ID is the unique identifier of the instance this object belongs to. Mandatory, unless a new instance to create is given.', verbose_name='GenioPay User ID'),
        ),
    ]
