# Generated by Django 4.2.9 on 2024-01-12 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_user_geniopay_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='geniopay_key',
            field=models.CharField(blank=True, help_text='this stores the users auth key', max_length=100, null=True, verbose_name='GenioPay Auth Token'),
        ),
    ]
