# Generated by Django 4.2.9 on 2024-01-13 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_user_geniopay_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='accept_terms',
            field=models.BooleanField(blank=True, default=False, help_text='Agreements collected from the user, such as acceptance of terms and conditions, or opt in for marketing', null=True, verbose_name='Accept Terms'),
        ),
    ]
