# Generated by Django 4.2.9 on 2024-01-13 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_alter_user_accept_terms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='geniopay_user_id',
            field=models.UUIDField(blank=True, help_text='GenioPay user ID is the unique identifier of the instance this object belongs to. Mandatory, unless a new instance to create is given.', null=True, verbose_name='GenioPay User ID'),
        ),
    ]
