# Generated by Django 4.2.9 on 2024-01-15 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_alter_user_options_user_created_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wallet_pin',
            field=models.CharField(blank=True, editable=False, help_text='this stores the users wallet pin', max_length=200, null=True, verbose_name='Wallet Pin'),
        ),
    ]
