# Generated by Django 4.2.9 on 2024-01-13 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0002_alter_accounttype_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttype',
            name='fee_margin',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Rate charged as transaction fee for transactions performed on Account.', max_digits=300, null=True, verbose_name='Transaction Fee Margin'),
        ),
        migrations.AlterField(
            model_name='accounttype',
            name='initial_deposit',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='The initial deposit is the amount to fund you Account to activate the Account.', max_digits=300, null=True, verbose_name='Initial Deposit'),
        ),
        migrations.AlterField(
            model_name='accounttype',
            name='interest_rate',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='The interest rate of the Account type.', max_digits=300, null=True, verbose_name='Interest Rate'),
        ),
        migrations.AlterField(
            model_name='accounttype',
            name='maintenance_fee',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='The unit maintenance fee of the amount', max_digits=300, null=True, verbose_name='Maintenance Fee'),
        ),
        migrations.AlterField(
            model_name='accounttype',
            name='max_deposit',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='The maximum amount to deposit on a Account', max_digits=300, null=True, verbose_name='Max Deposit'),
        ),
        migrations.AlterField(
            model_name='accounttype',
            name='max_withdrawal',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='The maximum amount to withdrawal on a Account', max_digits=300, null=True, verbose_name='Max Withdrawal'),
        ),
        migrations.AlterField(
            model_name='accounttype',
            name='min_balance',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='The minimum balance a Account. Without a Account holding a minimum balance, the Account will be rendered inactive.', max_digits=300, null=True, verbose_name='Min Balance'),
        ),
        migrations.AlterField(
            model_name='accounttype',
            name='min_deposit',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='The minimum amount to deposit on a Account', max_digits=300, null=True, verbose_name='Min Deposit'),
        ),
        migrations.AlterField(
            model_name='accounttype',
            name='min_withdrawal',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='The minimum amount to withdrawal on a Account', max_digits=300, null=True, verbose_name='Min Withdrawal'),
        ),
        migrations.AlterField(
            model_name='balance',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='The unit value of the amount', max_digits=300, null=True, verbose_name='Value'),
        ),
    ]
