# Generated by Django 4.2.9 on 2024-01-13 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transfer', '0003_alter_accounttype_fee_margin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='account_id',
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='account_user',
            field=models.ForeignKey(blank=True, help_text='The user for whom address belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User Profile'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='The unique identifier of an object.', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='user',
            field=models.EmailField(blank=True, help_text='TThe Profile ID of the User', max_length=254, null=True, verbose_name='User Account'),
        ),
    ]
