# Generated by Django 4.2.9 on 2024-01-13 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0004_remove_bankaccount_account_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttype',
            name='deleted',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the record was deleted. The date and time \n            are displayed in the Timezone from where request is made. \n            e.g. 2019-14-29T00:15:09Z for April 29, 2019 0:15:09 UTC', null=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='bankaddress',
            name='deleted',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the record was deleted. The date and time \n            are displayed in the Timezone from where request is made. \n            e.g. 2019-14-29T00:15:09Z for April 29, 2019 0:15:09 UTC', null=True, verbose_name='Created'),
        ),
    ]
