# Generated by Django 4.2.9 on 2024-01-13 23:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0005_alter_accounttype_deleted_alter_bankaddress_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='user',
            field=models.UUIDField(blank=True, default=uuid.uuid4, help_text='TThe Profile ID of the User', null=True, verbose_name='User Account'),
        ),
    ]
